[fastapi]

HOST = "127.0.0.1"
PORT = 8080

[mongodb]

HOST = "127.0.0.1"
PORT = 27017

[mongodb.databases]

# name of db = ["collection_name"]
user_db = ["users", "teams"]


[logging]

LOG_DIRS = [
    ['logs'],
    ['logs', 'core'],
    ['logs', 'database'],
    ['logs', 'users']
]
